import re
with open('bot-content.js', 'r') as f:
    content = f.read()
faqs = '''
    "braai": "Ja my bru, we can coat braai stands and grills! As long as it's metal. Send a photo on WhatsApp. 076 760 4350",
    "bbq": "Ja my bru, we can coat braai stands and grills! As long as it's metal. Send a photo on WhatsApp. 076 760 4350",
    "grill": "Ja my bru, we can coat braai stands and grills! As long as it's metal. Send a photo on WhatsApp. 076 760 4350",
    "weekend": "Closed weekends, my bru. Mon-Thu 8AM-4:45PM, Fri 8AM-2:45PM.",
    "saturday": "Closed weekends, my bru. Mon-Thu 8AM-4:45PM, Fri 8AM-2:45PM.",
    "sunday": "Closed weekends, my bru. Mon-Thu 8AM-4:45PM, Fri 8AM-2:45PM.",
    "public holiday": "Closed on public holidays. Mon-Thu 8AM-4:45PM, Fri 8AM-2:45PM.",
    "aluminium": "Ja, we coat aluminium! Needs proper etching first. Bring it through. 076 760 4350",
    "aluminum": "Ja, we coat aluminium! Needs proper etching first. Bring it through. 076 760 4350",
    "rust": "If you can see rust, blast it first! R8-R12/kg shotblasting then coat. Send a photo?",
    "rusted": "If you can see rust, blast it first! R8-R12/kg shotblasting then coat. Send a photo?",
    "corrosion": "If you can see rust, blast it first! R8-R12/kg shotblasting then coat. Send a photo?",
    "anodizing": "We don't do wet paint, anodizing, or galvanizing. Powder coating only — tougher and lasts 15-20 years.",
    "galvanizing": "We don't do wet paint, anodizing, or galvanizing. Powder coating only — tougher and lasts 15-20 years.",
    "wet paint": "We don't do wet paint, anodizing, or galvanizing. Powder coating only.",
    "durability": "Powder coating lasts 15-20 years. Chip-resistant, UV-stable, doesn't fade like wet paint.",
    "how long": "Powder coating lasts 15-20 years. Chip-resistant, UV-stable, doesn't fade like wet paint.",
    "lifespan": "Powder coating lasts 15-20 years. Chip-resistant, UV-stable, doesn't fade like wet paint.",
    "chip": "Powder coat is chip-resistant but not chip-proof. Small scratches can be touched up. Big damage needs re-coat.",
    "scratch": "Powder coat is chip-resistant but not chip-proof. Small scratches can be touched up.",
    "repair": "Powder coat is chip-resistant but not chip-proof. Big damage needs a re-blast and re-coat. Send a photo?",
    "colour": "20+ colours including RAL matches! Type *9* for GALLERY or WhatsApp Ridhor. 076 760 4350",
    "color": "20+ colours including RAL matches! Type *9* for GALLERY or WhatsApp Ridhor. 076 760 4350",
    "ral": "20+ colours including RAL matches! Type *9* for GALLERY or WhatsApp Ridhor. 076 760 4350",
    "temperature": "Standard powder coat handles up to 180C. For higher temps, special high-heat powder needed. 076 760 4350",
    "heat": "Standard powder coat handles up to 180C. For higher temps, special high-heat powder needed. 076 760 4350",
    "fire": "Standard powder coat handles up to 180C. For higher temps, special high-heat powder needed. 076 760 4350",
    "thickness": "Standard coat is 60-80 microns. We can go thicker if needed.",
    "micron": "Standard coat is 60-80 microns. We can go thicker if needed.",
    "prep": "Prep is 90% of the job! We shotblast first (R8-R12/kg) then coat. No shortcuts.",
    "preparation": "Prep is 90% of the job! We shotblast first (R8-R12/kg) then coat. No shortcuts.",
    "warranty": "We guarantee proper adhesion. If it peels due to our prep, we'll redo it. Lasts 15-20 years.",
    "guarantee": "We guarantee proper adhesion. If it peels due to our prep, we'll redo it.",
    "lead time": "Standard turnaround 3-5 working days. Big jobs or custom colours might take longer.",
    "turnaround": "Standard turnaround 3-5 working days. Big jobs or custom colours might take longer.",
    "minimum": "Minimum charge R350 for small jobs. But bring it through — we can batch small stuff.",
    "small job": "Minimum charge R350 for small jobs. But bring it through — we can batch small stuff.",
    "bulk": "Bulk discounts available for big runs! Send Ridhor your specs. 076 760 4350",
    "discount": "Bulk discounts available for big runs! Send Ridhor your specs. 076 760 4350",
    "volume": "Bulk discounts available for big runs! Send Ridhor your specs. 076 760 4350",
    "inspection": "Every job inspected before collection. Not happy? Tell us before you leave — we'll fix it.",
    "quality": "Every job inspected before collection. Not happy? Tell us before you leave — we'll fix it.",
    "transport": "We can arrange courier for out-of-town jobs. Or collect from 5 Jakaranda St, Blackheath.",
    "courier": "We can arrange courier for out-of-town jobs. Or collect from 5 Jakaranda St, Blackheath.",
    "outdoor": "Powder coating is perfect for outdoor use! UV-stable, rain-resistant, won't peel.",
    "outside": "Powder coating is perfect for outdoor use! UV-stable, rain-resistant, won't peel.",
    "weather": "Powder coating is perfect for outdoor use! UV-stable, rain-resistant, won't peel.",
    "indoor": "Ja, we coat indoor stuff too — furniture, fixtures, bike frames. Any metal.",
    "car part": "We coat car parts, rims, bumpers, bike frames. High-heat parts need special powder. 076 760 4350",
    "automotive": "We coat car parts, rims, bumpers, bike frames. High-heat parts need special powder. 076 760 4350",
    "exhaust": "High-heat powder needed for exhausts. We coat manifolds and headers. 076 760 4350",
    "motorcycle": "Bike frames, motorcycle parts, rims — we coat them all! Send a photo. 076 760 4350",
    "bike frame": "Bike frames, motorcycle parts, rims — we coat them all! Send a photo. 076 760 4350",
    "bicycle": "Bike frames, motorcycle parts, rims — we coat them all! Send a photo. 076 760 4350",
    "fence": "Fences, palisades, balustrades, railings — we coat them all! Send photos for quote.",
    "palisade": "Fences, palisades, balustrades, railings — we coat them all! Send photos for quote.",
    "balustrade": "Fences, palisades, balustrades, railings — we coat them all! Send photos for quote.",
    "railing": "Fences, palisades, balustrades, railings — we coat them all! Send photos for quote.",
    "furniture": "Outdoor furniture, tables, chairs, patio sets — we coat them! Send photos.",
    "table": "Outdoor furniture, tables, chairs, patio sets — we coat them! Send photos.",
    "chair": "Outdoor furniture, tables, chairs, patio sets — we coat them! Send photos.",
    "patio": "Outdoor furniture, tables, chairs, patio sets — we coat them! Send photos.",
    "tool": "Tools, machinery, industrial equipment — we coat them all. Bring it through. 076 760 4350",
    "machinery": "Tools, machinery, industrial equipment — we coat them all. Bring it through. 076 760 4350",
    "equipment": "Tools, machinery, industrial equipment — we coat them all. Bring it through. 076 760 4350",
    "industrial": "Tools, machinery, industrial equipment — we coat them all. Bring it through. 076 760 4350",
    "food safe": "We have food-safe powder coatings for kitchen equipment. Tell Ridhor. 076 760 4350",
    "kitchen": "We have food-safe powder coatings for kitchen equipment. Tell Ridhor. 076 760 4350",
    "food grade": "We have food-safe powder coatings for kitchen equipment. Tell Ridhor. 076 760 4350",
    "diy": "DIY powder coating is tricky — need blast cabinet, spray booth, oven. Bring it to us. Proper result.",
    "do it myself": "DIY powder coating is tricky — need blast cabinet, spray booth, oven. Bring it to us.",
    "home": "DIY powder coating is tricky — need blast cabinet, spray booth, oven. Bring it to us.",
    "eco": "Powder coating is eco-friendly! No solvents, no VOCs, minimal waste. Greener than wet paint.",
    "environment": "Powder coating is eco-friendly! No solvents, no VOCs, minimal waste.",
    "green": "Powder coating is eco-friendly! No solvents, no VOCs, minimal waste.",
    "voc": "Powder coating is eco-friendly! No solvents, no VOCs, minimal waste.",
    "electrostatic": "We blast, spray charged powder, bake at 180-200C. Powder melts into tough skin. 15-20 years!",
    "how it works": "We blast, spray charged powder, bake at 180-200C. Powder melts into tough skin. 15-20 years!",
    "process": "We blast, spray charged powder, bake at 180-200C. Powder melts into tough skin. 15-20 years!",
    "sandblasting": "We do shotblasting — cleaner, more controlled. R8-R12/kg. Perfect prep for coating.",
    "sand blast": "We do shotblasting — cleaner, more controlled. R8-R12/kg. Perfect prep for coating.",
    "grit blasting": "We do shotblasting — cleaner, more controlled. R8-R12/kg. Perfect prep for coating.",
    "masking": "We mask threads, holes, mating surfaces. Tell us what to keep clean.",
    "thread": "We mask threads, bolts, fasteners so they stay clean. Or coat them fully — your choice.",
    "bolt": "We mask threads, bolts, fasteners so they stay clean. Or coat them fully — your choice.",
    "hole": "We mask holes and recesses. Tell us what needs to stay clean.",
    "sample": "Test pieces and colour swatches available. Small fee. WhatsApp Ridhor. 076 760 4350",
    "test piece": "Test pieces and colour swatches available. Small fee. WhatsApp Ridhor. 076 760 4350",
    "swatch": "Test pieces and colour swatches available. Small fee. WhatsApp Ridhor. 076 760 4350",
    "bee": "Let me get Ridhor on this — WhatsApp him on 076 760 4350.",
    "b-bbee": "Let me get Ridhor on this — WhatsApp him on 076 760 4350.",
    "payment method": "COD only, my bru. Cash on collection. No EFT, no cards. Payment before release.",
    "eft": "COD only, my bru. Cash on collection. No EFT, no cards. Payment before release.",
    "card": "COD only, my bru. Cash on collection. No EFT, no cards. Payment before release.",
    "credit card": "COD only, my bru. Cash on collection. No EFT, no cards. Payment before release.",
    "quote": "Type *3* for a formal quote, or tell me what you need priced — gates, rims, steel, shotblasting.",
    "estimate": "Type *3* for a formal quote, or tell me what you need priced — gates, rims, steel, shotblasting.",
    "price": "Type *3* for a formal quote, or tell me what you need priced — gates, rims, steel, shotblasting.",
    "how much": "Type *3* for a formal quote, or tell me what you need priced — gates, rims, steel, shotblasting.",
    "contact": "Ridhor: 076 760 4350. Office: 021 905 2912. Email: populier@mweb.co.za",
    "phone": "Ridhor: 076 760 4350. Office: 021 905 2912. Email: populier@mweb.co.za",
    "email": "Ridhor: 076 760 4350. Office: 021 905 2912. Email: populier@mweb.co.za",
    "whatsap": "Ridhor: 076 760 4350. Office: 021 905 2912. Email: populier@mweb.co.za",
    "location": "5 Jakaranda Street, Blackheath, Cape Town. Mon-Thu 8-4:45, Fri 8-2:45.",
    "address": "5 Jakaranda Street, Blackheath, Cape Town. Mon-Thu 8-4:45, Fri 8-2:45.",
    "where": "5 Jakaranda Street, Blackheath, Cape Town. Mon-Thu 8-4:45, Fri 8-2:45.",
    "direction": "5 Jakaranda Street, Blackheath, Cape Town. Mon-Thu 8-4:45, Fri 8-2:45.",
    "hours": "Mon-Thu 8AM-4:45PM, Fri 8AM-2:45PM. Closed weekends and public holidays.",
    "open": "Mon-Thu 8AM-4:45PM, Fri 8AM-2:45PM. Closed weekends and public holidays.",
    "close": "Mon-Thu 8AM-4:45PM, Fri 8AM-2:45PM. Closed weekends and public holidays.",
    "time": "Mon-Thu 8AM-4:45PM, Fri 8AM-2:45PM. Closed weekends and public holidays.",
    "delivery": "Type *6* for delivery. R150 Cape Town metro. Free collection.",
    "collect": "Type *6* for delivery. R150 Cape Town metro. Free collection.",
    "storage": "Free storage 7 days. After that 7% daily. Collect on time, my bru!",
    "complaint": "Let me get Ridhor — WhatsApp him on 076 760 4350. He'll sort it out.",
    "problem": "Let me get Ridhor — WhatsApp him on 076 760 4350. He'll sort it out.",
    "unhappy": "Let me get Ridhor — WhatsApp him on 076 760 4350. He'll sort it out.",
    "refund": "Let me get Ridhor — WhatsApp him on 076 760 4350. He'll sort it out.",
    "review": "Type *11* to leave a Google review! Helps other customers find us.",
    "google": "Type *11* to leave a Google review! Helps other customers find us.",
    "rating": "Type *11* to leave a Google review! Helps other customers find us.",
    "social": "Type *10* to follow us on Facebook and TikTok. Before/after shots posted regularly!",
    "facebook": "Type *10* to follow us on Facebook and TikTok. Before/after shots posted regularly!",
    "instagram": "Type *10* to follow us on Facebook and TikTok. Before/after shots posted regularly!",
    "tiktok": "Type *10* to follow us on Facebook and TikTok. Before/after shots posted regularly!",
    "tip": "TPS Wisdom: Prep is 90% of the job. Type *15* for more Solomon Truth Bombs.",
    "advice": "TPS Wisdom: Prep is 90% of the job. Type *15* for more Solomon Truth Bombs.",
    "recommend": "TPS Wisdom: Prep is 90% of the job. Type *15* for more Solomon Truth Bombs.",
    "history": "Solomon Coatings since 1988. One compressor and a dream. Cape Town legends.",
    "since when": "Solomon Coatings since 1988. One compressor and a dream. Cape Town legends.",
    "experience": "Solomon Coatings since 1988. One compressor and a dream. Cape Town legends.",
    "owner": "Ridhor runs the show. WhatsApp him: 076 760 4350. Coating since the 90s.",
    "ridhor": "Ridhor runs the show. WhatsApp him: 076 760 4350. Coating since the 90s.",
    "solomon": "Ridhor runs the show. WhatsApp him: 076 760 4350. Coating since the 90s.",
    "job": "We're always looking for good people! Send CV to populier@mweb.co.za or WhatsApp. 076 760 4350",
    "hiring": "We're always looking for good people! Send CV to populier@mweb.co.za or WhatsApp. 076 760 4350",
    "vacancy": "We're always looking for good people! Send CV to populier@mweb.co.za or WhatsApp. 076 760 4350",
    "apprentice": "We take apprentices for practical training. WhatsApp Ridhor. 076 760 4350",
    "training": "We take apprentices for practical training. WhatsApp Ridhor. 076 760 4350",
    "maintenance": "Just wash with soap and water. No wax. No abrasive cleaners. Stays fresh for years.",
    "clean": "Just wash with soap and water. No wax. No abrasive cleaners. Stays fresh for years.",
    "wash": "Just wash with soap and water. No wax. No abrasive cleaners. Stays fresh for years.",
    "uv": "Our powders are UV-stable. Won't fade or chalk in the sun.",
    "sun": "Our powders are UV-stable. Won't fade or chalk in the sun.",
    "fade": "Our powders are UV-stable. Won't fade or chalk in the sun.",
    "salt": "Coastal areas need extra prep — salt is sneaky. Corrosion-resistant primers used. 076 760 4350",
    "coastal": "Coastal areas need extra prep — salt is sneaky. Corrosion-resistant primers used. 076 760 4350",
    "sea": "Coastal areas need extra prep — salt is sneaky. Corrosion-resistant primers used. 076 760 4350",
    "oil": "Petrol, diesel, oil don't affect powder coating. Clean spills quickly.",
    "grease": "Petrol, diesel, oil don't affect powder coating. Clean spills quickly.",
    "petrol": "Petrol, diesel, oil don't affect powder coating. Clean spills quickly.",
    "diesel": "Petrol, diesel, oil don't affect powder coating. Clean spills quickly.",
    "acid": "Acids and strong solvents can damage powder coat. Wipe spills immediately.",
    "chemical": "Acids and strong solvents can damage powder coat. Wipe spills immediately.",
    "dent": "We don't do panel beating or welding. Fix dents first, then bring to us for coating.",
    "bend": "We don't do panel beating or welding. Fix dents first, then bring to us for coating.",
    "weld": "We don't do welding — we coat what you bring. We know good fabricators. Ask Ridhor.",
    "fabrication": "We don't do welding — we coat what you bring. We know good fabricators. Ask Ridhor.",
    "glass": "Powder coating is for metal only. No glass, wood, plastic, or rubber.",
    "wood": "Powder coating is for metal only. No glass, wood, plastic, or rubber.",
    "plastic": "Powder coating is for metal only. No glass, wood, plastic, or rubber.",
    "rubber": "Powder coating is for metal only. No glass, wood, plastic, or rubber.",
    "chrome": "We don't do chrome or mirror finishes. Powder gives smooth colour — matte, satin, gloss.",
    "textured": "Ja, we do textured finishes! Wrinkle, hammer tone, vein patterns available. 076 760 4350",
    "wrinkle": "Ja, we do textured finishes! Wrinkle, hammer tone, vein patterns available. 076 760 4350",
    "hammer": "Ja, we do textured finishes! Wrinkle, hammer tone, vein patterns available. 076 760 4350",
    "metallic": "Metallic, pearl, candy colours available! Tell Ridhor your dream colour. 076 760 4350",
    "pearl": "Metallic, pearl, candy colours available! Tell Ridhor your dream colour. 076 760 4350",
    "candy": "Metallic, pearl, candy colours available! Tell Ridhor your dream colour. 076 760 4350",
    "gloss": "Gloss, satin, matte, textured — your choice! Gloss shiny, matte modern, satin middle ground.",
    "matte": "Gloss, satin, matte, textured — your choice! Gloss shiny, matte modern, satin middle ground.",
    "satin": "Gloss, satin, matte, textured — your choice! Gloss shiny, matte modern, satin middle ground.",
    "finish": "Gloss, satin, matte, textured — your choice! Gloss shiny, matte modern, satin middle ground.",
    "primer": "We use zinc-rich primer for steel, etch primer for aluminium. Included in prep price.",
    "galvanized": "We can coat over galvanizing — needs special prep. Zinc can outgas. Tell Ridhor. 076 760 4350",
    "stainless": "Stainless steel can be coated — needs special etching. We know the process. 076 760 4350",
    "inox": "Stainless steel can be coated — needs special etching. We know the process. 076 760 4350",
    "cast": "Cast iron and cast aluminium — we coat them! Need extra cleaning. Tell Ridhor. 076 760 4350",
    "iron": "Cast iron and cast aluminium — we coat them! Need extra cleaning. Tell Ridhor. 076 760 4350",
    "old": "Restoration is our favourite! Old gates, vintage furniture — we bring them back. Send photos.",
    "restore": "Restoration is our favourite! Old gates, vintage furniture — we bring them back. Send photos.",
    "refurbish": "Restoration is our favourite! Old gates, vintage furniture — we bring them back. Send photos.",
    "vintage": "Restoration is our favourite! Old gates, vintage furniture — we bring them back. Send photos.",
    "new": "New steel needs degreasing and light blasting before coating. We handle all prep.",
    "second hand": "Second-hand stuff is fine — we blast off old paint and rust, then coat.",
    "used": "Second-hand stuff is fine — we blast off old paint and rust, then coat.",
    "sheet": "Sheet metal, plates, panels — R175-R350/sqm. Send specs for quote.",
    "plate": "Sheet metal, plates, panels — R175-R350/sqm. Send specs for quote.",
    "panel": "Sheet metal, plates, panels — R175-R350/sqm. Send specs for quote.",
    "tube": "Tubes, pipes, round bars — no problem. We have jigs to hold them.",
    "pipe": "Tubes, pipes, round bars — no problem. We have jigs to hold them.",
    "wire": "Wire mesh, grids, screens — we coat them! Extra care needed. Tell Ridhor mesh size. 076 760 4350",
    "mesh": "Wire mesh, grids, screens — we coat them! Extra care needed. Tell Ridhor mesh size. 076 760 4350",
    "grid": "Wire mesh, grids, screens — we coat them! Extra care needed. Tell Ridhor mesh size. 076 760 4350",
    "spring": "Springs and flexible parts tricky — powder can crack when flexing. Tell Ridhor. 076 760 4350",
    "flexible": "Springs and flexible parts tricky — powder can crack when flexing. Tell Ridhor. 076 760 4350",
    "sharp": "Sharp edges need extra powder for full coverage. Standard practice — we build up edges.",
    "edge": "Sharp edges need extra powder for full coverage. Standard practice — we build up edges.",
    "logo": "We can mask logos and text, or coat over them. Custom branding — speak to Ridhor. 076 760 4350",
    "brand": "We can mask logos and text, or coat over them. Custom branding — speak to Ridhor. 076 760 4350",
    "sign": "Signs, displays, stands — we coat metal frames and backing. For printed signs, frame only.",
    "display": "Signs, displays, stands — we coat metal frames and backing. For printed signs, frame only.",
    "gym": "Gym equipment, sports gear — tough finish for tough use. Send photos. 076 760 4350",
    "fitness": "Gym equipment, sports gear — tough finish for tough use. Send photos. 076 760 4350",
    "playground": "Playground equipment, school furniture — safe, durable, colourful. Tell us your spec.",
    "school": "Playground equipment, school furniture — safe, durable, colourful. Tell us your spec.",
    "farm": "Farm equipment, tractor parts — tough enough for the veld. Send photos. 076 760 4350",
    "tractor": "Farm equipment, tractor parts — tough enough for the veld. Send photos. 076 760 4350",
    "agricultural": "Farm equipment, tractor parts — tough enough for the veld. Send photos. 076 760 4350",
    "mining": "Mining equipment, heavy plant — corrosion-resistant finishes. Tell Ridhor. 076 760 4350",
    "heavy": "Mining equipment, heavy plant — corrosion-resistant finishes. Tell Ridhor. 076 760 4350",
    "marine": "Marine equipment, boat parts — salt-resistant finishes. Tell Ridhor. 076 760 4350",
    "boat": "Marine equipment, boat parts — salt-resistant finishes. Tell Ridhor. 076 760 4350",
    "art": "Art pieces, sculptures — we love these! Bring your vision. Send photos. 076 760 4350",
    "sculpture": "Art pieces, sculptures — we love these! Bring your vision. Send photos. 076 760 4350",
    "decorative": "Art pieces, sculptures — we love these! Bring your vision. Send photos. 076 760 4350",
    "gift": "Custom gifts, personalised items — nameplates, keyrings. Tell us your idea. 076 760 4350",
    "custom": "Custom gifts, personalised items — nameplates, keyrings. Tell us your idea. 076 760 4350",
    "prototype": "Prototypes and one-offs welcome! Bring your idea. 076 760 4350",
    "one-off": "Prototypes and one-offs welcome! Bring your idea. 076 760 4350",
    "unique": "Prototypes and one-offs welcome! Bring your idea. 076 760 4350",
    "emergency": "Rush jobs possible depending on queue. Extra charge might apply. 076 760 4350",
    "urgent": "Rush jobs possible depending on queue. Extra charge might apply. 076 760 4350",
    "rush": "Rush jobs possible depending on queue. Extra charge might apply. 076 760 4350",
    "asap": "Rush jobs possible depending on queue. Extra charge might apply. 076 760 4350",
    "cancel": "No problem, cancelled. Type *menu* to go back to the main list.",
    "stop": "No problem, cancelled. Type *menu* to go back to the main list.",
    "thank": "Only a pleasure! Thanks for choosing Solomon Coatings since 1988.",
    "thanks": "Only a pleasure! Thanks for choosing Solomon Coatings since 1988.",
    "dankie": "Only a pleasure! Thanks for choosing Solomon Coatings since 1988.",
    "bye": "Cheers! Sien jou later. Bring that item through when you're ready.",
    "referral": "We love referrals! Tell your mates. 060 507 4461. Word of mouth since 1988!",
    "friend": "We love referrals! Tell your mates. 060 507 4461. Word of mouth since 1988!",
'''

last_entry_pattern = r'"15":\s*"[^"]*"'
match = re.search(last_entry_pattern, content)
if match:
    insert_pos = match.end()
    new_content = content[:insert_pos] + ',' + faqs + content[insert_pos:]
else:
    print("Could not find QR entry point")
    exit(1)

with open('bot-content.js', 'w') as f:
    f.write(new_content)
print("FAQs added to bot-content.js QR object")
