var greetings = [
  "Howzit! SC here, lekker ready to help - what are we coating today?",
  "SC here - ready to get down and dirty with your metal. What is up?",
  "SC online. Looking for a hard finish? Let us talk shop.",
  "Yo, it is SC. I am here to make sure your parts get the attention they deserve.",
  "SC here. Ready to give your project a real heavy-duty coat - what you got?",
  "SC live. You bring the steel, I will bring the finish - let us get it on.",
  "Welcome to Solomon Coatings. How can I assist you today?",
  "Hello! Thanks for choosing Solomon Coatings; what can I help you with?",
  "Solomon Coatings support here - how can I help with your project?",
  "Welcome to Solomon Coatings. Ready to start your next project?",
  "Hi from Solomon Coatings! What is on your mind today?",
  "Hello, this is SC. How can I assist with your coating project today?",
  "Welcome to SC. Please let me know how I can help you.",
  "SC here. I am available to assist with your technical or service requests.",
  "Hello, you have reached SC. How can I help you move your project forward?",
  "SC online. Please detail your project needs so I can assist you.",
  "Yo! SC online and hyped to assist - what is on the bench, chief?",
  "Howzit! SC here, ready to roll - what are we finishing today?",
  "Howzit! SC live and ready to get cracking - what can I sort out for you?",
  "Yo! SC here - ready to help, what are we working on?",
  "Welcome. This is SC. Please state the nature of your inquiry.",
  "Greetings. You are connected to SC. How may I assist you?",
  "Thank you for contacting SC. Please provide your project details.",
  "SC is online. How may I facilitate your request today?",
  "Welcome to the SC interface. Awaiting your instructions.",
  "SC here. Please specify the service you require.",
  "Greetings. SC is ready to process your request.",
  "Connected to SC. How can I be of service?",
  "SC digital assistant active. Please state your needs.",
  "Thank you for reaching out to SC. How may we help?",
  "SC terminal online. Please provide your project specifications.",
  "Welcome. SC is currently standing by for your inquiry.",
  "Greetings. Please specify how SC can assist with your requirements.",
  "SC here. We are prepared to address your technical inquiry.",
  "Connection established. Please state your requirements for SC.",
  "Welcome to SC. How can I assist you with your project?",
  "SC online. Please provide details regarding your inquiry.",
  "Greetings. I am SC, your automated assistant. How can I help?",
  "SC is ready. Please proceed with your inquiry.",
  "Thank you for contacting SC. How may we facilitate your project?"
];
function randomGreeting(){ return greetings[Math.floor(Math.random()*greetings.length)]; }
module.exports = { randomGreeting };
